name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::883886326619:role/github-actions-ecr-role
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t project7-github-actions-ecr ./github-actions-ecr-cicd

      - name: Tag Docker image
        run: docker tag project7-github-actions-ecr:latest 883886326619.dkr.ecr.eu-central-1.amazonaws.com/project7-github-actions-ecr:latest

      - name: Push Docker image to ECR
        run: docker push 883886326619.dkr.ecr.eu-central-1.amazonaws.com/project7-github-actions-ecr:latest
